// Static configuration and seed data for the EMS app.
// No JSX/icons here so this module can be imported anywhere safely.

export const BOARD_ROLES = ["BOME", "BOEN"];
export const COLLEGE_ROLES = ["College User", "College Staff"];
export const VERIFIER_ROLES = ["Board Verifier"];
export const APPROVER_ROLES = ["Board Approver"];
export const ALL_ROLES = [
  "Super Admin",
  "BOME",
  "BOEN",
  "College User",
  "College Staff",
  "Board Verifier",
  "Board Approver",
  "Reports User",
  "Institution",
];

export const STATUS_OPTIONS = [
  "Active",
  "Inactive",
  "Draft",
  "Submitted",
  "Verified",
  "Approved",
  "Rejected",
  "Sent Back",
];

export const ENTITY_FIELDS = {
  user: [
    ["name", "Name"],
    ["role", "Role", ALL_ROLES],
    ["office", "College / Board"],
    ["designation", "Designation"],
    ["mobile", "Mobile"],
    ["email", "Email"],
    ["status", "Status", ["Active", "Inactive"]],
  ],
  role: [
    ["name", "User"],
    ["role", "Assigned Role", ALL_ROLES],
    [
      "category",
      "Role Category",
      ["Admin Role", "Staff / Official Role", "Feature Role", "Reports Role"],
    ],
    ["module", "Module"],
    ["status", "Status", ["Active", "Inactive"]],
  ],
  mapping: [
    ["office", "Office"],
    ["reportsTo", "Reports To"],
    ["workflow", "Workflow"],
    ["board", "Board", BOARD_ROLES],
    ["status", "Status", ["Active", "Inactive"]],
  ],
  feature: [
    ["feature", "Feature"],
    ["module", "Module", ["Student", "Examination", "Marks", "Admin", "MIS"]],
    ["workflow", "Workflow"],
    ["status", "Status", ["Active", "Inactive"]],
  ],
  master: [
    ["name", "Name"],
    ["type", "Type", ["Institute", "Course", "Subject", "Term"]],
    ["code", "Code"],
    ["effectiveFrom", "Effective From"],
    ["status", "Status", ["Active", "Inactive"]],
  ],
  student: [
    ["student", "Student"],
    ["studentId", "Student ID"],
    ["college", "College"],
    ["course", "Course"],
    ["term", "Term", ["Term 1", "Term 2", "Term 3", "Term 4"]],
    [
      "status",
      "Status",
      ["Draft", "Submitted", "Verified", "Approved", "Rejected", "Sent Back"],
    ],
  ],
  education: [
    ["student", "Student"],
    ["level", "Level", ["X", "XII", "Others"]],
    ["board", "Board / Exam"],
    ["institution", "School / College"],
    ["year", "Year"],
    ["status", "Status", ["Draft", "Submitted", "Verified", "Approved"]],
  ],
  document: [
    ["student", "Student"],
    ["document", "Document"],
    [
      "purpose",
      "Purpose",
      ["Identity", "Date of Birth", "Address", "Education"],
    ],
    ["uploadedOn", "Uploaded On"],
    ["status", "Status", ["Submitted", "Verified", "Rejected", "Sent Back"]],
  ],
  subjectSelection: [
    ["college", "College"],
    ["course", "Course"],
    ["term", "Term", ["Term 1", "Term 2", "Term 3", "Term 4"]],
    ["subjects", "Subjects"],
    ["effectiveFrom", "Effective From"],
    ["status", "Status", ["Active", "Inactive"]],
  ],
  schedule: [
    ["college", "College"],
    ["course", "Course"],
    ["term", "Term", ["Term 1", "Term 2", "Term 3", "Term 4"]],
    ["examType", "Exam Type", ["Mid Term", "End Term"]],
    ["date", "Date"],
    [
      "status",
      "Status",
      ["Draft", "Submitted", "Verified", "Approved", "Sent Back"],
    ],
  ],
  attendance: [
    ["student", "Student"],
    ["subject", "Subject"],
    ["examType", "Exam Type", ["Mid Term", "End Term"]],
    ["attendance", "Attendance", ["Present", "Absent"]],
    ["uploadedBy", "Uploaded By"],
    ["status", "Status", ["Submitted", "Verified", "Approved"]],
  ],
  subjectMarks: [
    ["subject", "Subject"],
    ["course", "Course"],
    ["term", "Term", ["Term 1", "Term 2", "Term 3", "Term 4"]],
    ["totalMarks", "Total Marks"],
    ["passMarks", "Pass Marks"],
    ["status", "Status", ["Draft", "Submitted", "Verified", "Approved"]],
  ],
  studentMarks: [
    ["student", "Student"],
    ["subject", "Subject"],
    ["internal", "Internal"],
    ["exam", "Exam"],
    ["result", "Result", ["Pass", "Fail"]],
    [
      "status",
      "Status",
      ["Draft", "Submitted", "Verified", "Approved", "Sent Back"],
    ],
  ],
  marksheet: [
    ["student", "Student"],
    ["registrationNo", "Registration No."],
    ["course", "Course"],
    [
      "division",
      "Division",
      ["Distinction", "First Class", "Second Class", "Third Class", "Fail"],
    ],
    ["referenceNo", "Reference No."],
    ["status", "Status", ["Submitted", "Verified", "Approved"]],
  ],
  report: [
    ["name", "Report"],
    ["module", "Module", ["Student", "Examination", "Marks"]],
    ["frequency", "Frequency", ["Daily", "Weekly", "Monthly", "On Demand"]],
    ["owner", "Owner"],
    ["status", "Status", ["Active", "Inactive"]],
  ],
  institution: [
    ["name", "Institution"],
    ["region", "Region"],
    ["status", "Status", ["Active", "Inactive"]],
  ],
  course: [
    ["name", "Course"],
    ["status", "Status", ["Active", "Inactive"]],
  ],
  boardSubject: [
    ["subject", "Subject"],
    ["year", "Year"],
    ["semester", "Semester"],
    ["priority", "Priority"],
    ["status", "Status", ["Active", "Inactive"]],
  ],
  institutionStudent: [
    ["name", "Student Name"],
    ["registerNo", "Register No"],
    ["term", "Term"],
    ["status", "Status", ["Active", "Inactive"]],
  ],
  institutionMarks: [
    ["subject", "Subject"],
    ["internal", "Internal"],
    ["exam", "Exam"],
    ["result", "Result", ["Pass", "Fail"]],
    ["status", "Status", ["Active", "Inactive"]],
  ],
  institutionAttendance: [
    ["subject", "Subject"],
    ["examType", "Exam Type", ["Mid Term", "End Term"]],
    ["attendance", "Attendance", ["Present", "Absent"]],
    ["status", "Status", ["Active", "Inactive"]],
  ],
};

export const ENTITY_COLUMNS = {
  users: ["name", "role", "office", "designation", "mobile", "status"],
  roles: ["name", "role", "category", "module", "status"],
  mappings: ["office", "reportsTo", "workflow", "board", "status"],
  features: ["feature", "module", "workflow", "status"],
  masters: ["name", "type", "code", "effectiveFrom", "status"],
  students: ["student", "studentId", "college", "course", "term", "status"],
  education: ["student", "level", "board", "institution", "year", "status"],
  documents: ["student", "document", "purpose", "uploadedOn", "status"],
  subjectSelections: [
    "college",
    "course",
    "term",
    "subjects",
    "effectiveFrom",
    "status",
  ],
  schedules: ["college", "course", "term", "examType", "date", "status"],
  attendance: [
    "student",
    "subject",
    "examType",
    "attendance",
    "uploadedBy",
    "status",
  ],
  subjectMarks: [
    "subject",
    "course",
    "term",
    "totalMarks",
    "passMarks",
    "status",
  ],
  studentMarks: [
    "student",
    "subject",
    "internal",
    "exam",
    "result",
    "status",
  ],
  marksheets: [
    "student",
    "registrationNo",
    "course",
    "division",
    "referenceNo",
    "status",
  ],
  reports: ["name", "module", "frequency", "owner", "status"],
  institutions: ["name", "region", "status"],
  courses: ["name", "status"],
  boardSubjects: ["subject", "year", "semester", "priority", "status"],
  institutionStudents: ["name", "registerNo", "term", "status"],
  institutionMarks: ["subject", "internal", "exam", "result", "status"],
  institutionAttendance: ["subject", "examType", "attendance", "status"],
  pendingChanges: ["entityType", "action", "summary", "status", "requestedDate"],
};

export const FIELD_LABELS = {
  name: "Name",
  role: "Role",
  office: "Office",
  designation: "Designation",
  mobile: "Mobile",
  email: "Email",
  status: "Status",
  category: "Category",
  module: "Module",
  reportsTo: "Reports To",
  workflow: "Workflow",
  board: "Board",
  feature: "Feature",
  type: "Type",
  code: "Code",
  effectiveFrom: "Effective From",
  student: "Student",
  studentId: "Student ID",
  college: "College",
  course: "Course",
  term: "Term",
  level: "Level",
  institution: "Institution",
  year: "Year",
  document: "Document",
  purpose: "Purpose",
  uploadedOn: "Uploaded On",
  subjects: "Subjects",
  examType: "Exam Type",
  date: "Date",
  subject: "Subject",
  attendance: "Attendance",
  uploadedBy: "Uploaded By",
  totalMarks: "Total",
  passMarks: "Pass",
  internal: "Internal",
  exam: "Exam",
  result: "Result",
  registrationNo: "Registration No.",
  division: "Division",
  referenceNo: "Reference No.",
  frequency: "Frequency",
  owner: "Owner",
  region: "Region",
  duration: "Duration",
  semester: "Semester",
  priority: "Priority",
};

export const SEED_DATA = {
  users: [
    {
      id: 1,
      name: "Dr. Meera Rao",
      role: "Super Admin",
      office: "Directorate",
      designation: "System Owner",
      mobile: "9876500011",
      email: "meera.rao@gov.in",
      status: "Active",
    },
    {
      id: 2,
      name: "BOME Registrar",
      role: "BOME",
      office: "Board of Medical Education",
      designation: "Registrar",
      mobile: "9876500022",
      email: "bome@gov.in",
      status: "Active",
    },
    {
      id: 3,
      name: "BOEN Registrar",
      role: "BOEN",
      office: "Board of Examination in Nursing",
      designation: "Registrar",
      mobile: "9876500033",
      email: "boen@gov.in",
      status: "Active",
    },
    {
      id: 4,
      name: "College Coordinator",
      role: "College User",
      office: "Mother Theresa Institute",
      designation: "Coordinator",
      mobile: "9876500044",
      email: "college@gov.in",
      status: "Active",
    },
    {
      id: 5,
      name: "Board Checker",
      role: "Board Verifier",
      office: "BOME",
      designation: "Verifier",
      mobile: "9876500055",
      email: "checker@gov.in",
      status: "Active",
    },
    {
      id: 6,
      name: "Board Approver",
      role: "Board Approver",
      office: "BOEN",
      designation: "Approver",
      mobile: "9876500066",
      email: "approver@gov.in",
      status: "Inactive",
    },
  ],
  roles: [
    {
      id: 1,
      name: "Dr. Meera Rao",
      role: "Super Admin",
      category: "Admin Role",
      module: "Admin",
      status: "Active",
    },
    {
      id: 2,
      name: "BOME Registrar",
      role: "BOME",
      category: "Staff / Official Role",
      module: "Board Workflows",
      status: "Active",
    },
    {
      id: 3,
      name: "Reports Desk",
      role: "Reports User",
      category: "Reports Role",
      module: "MIS",
      status: "Active",
    },
  ],
  mappings: [
    {
      id: 1,
      office: "Mother Theresa Institute",
      reportsTo: "BOME",
      workflow: "Student Verification",
      board: "BOME",
      status: "Active",
    },
    {
      id: 2,
      office: "Nursing College",
      reportsTo: "BOEN",
      workflow: "Marks Approval",
      board: "BOEN",
      status: "Active",
    },
  ],
  features: [
    {
      id: 1,
      feature: "Bulk Student Approval",
      module: "Student",
      workflow: "Board approval with digital signature",
      status: "Active",
    },
    {
      id: 2,
      feature: "Digilocker Marksheet",
      module: "Marks",
      workflow: "Post approval publication",
      status: "Inactive",
    },
    {
      id: 3,
      feature: "Holiday Schedule Alerts",
      module: "Examination",
      workflow: "Exam date validation",
      status: "Active",
    },
  ],
  masters: [
    {
      id: 1,
      name: "Mother Theresa Institute",
      type: "Institute",
      code: "MTI",
      effectiveFrom: "2025-09-01",
      status: "Active",
    },
    {
      id: 2,
      name: "Diploma in General Nursing",
      type: "Course",
      code: "DGN",
      effectiveFrom: "2025-09-01",
      status: "Active",
    },
    {
      id: 3,
      name: "Anatomy",
      type: "Subject",
      code: "ANA101",
      effectiveFrom: "2025-09-01",
      status: "Active",
    },
    {
      id: 4,
      name: "Term 1",
      type: "Term",
      code: "T1",
      effectiveFrom: "2025-09-01",
      status: "Active",
    },
  ],
  students: [
    {
      id: 1,
      student: "Asha Kumar",
      studentId: "STU-1001",
      college: "Mother Theresa Institute",
      course: "Diploma in General Nursing",
      term: "Term 1",
      status: "Submitted",
    },
    {
      id: 2,
      student: "Nivin Raj",
      studentId: "STU-1002",
      college: "Mother Theresa Institute",
      course: "Diploma in Medical Lab Technology",
      term: "Term 2",
      status: "Verified",
    },
    {
      id: 3,
      student: "Sara D'Souza",
      studentId: "STU-1003",
      college: "Nursing College",
      course: "Diploma in General Nursing",
      term: "Term 1",
      status: "Approved",
    },
  ],
  education: [
    {
      id: 1,
      student: "Asha Kumar",
      level: "XII",
      board: "State Board",
      institution: "Govt Higher Secondary School",
      year: "2024",
      status: "Submitted",
    },
    {
      id: 2,
      student: "Nivin Raj",
      level: "XII",
      board: "CBSE",
      institution: "Central School",
      year: "2023",
      status: "Approved",
    },
  ],
  documents: [
    {
      id: 1,
      student: "Asha Kumar",
      document: "Date of Birth Certificate",
      purpose: "Date of Birth",
      uploadedOn: "2026-06-01",
      status: "Submitted",
    },
    {
      id: 2,
      student: "Sara D'Souza",
      document: "Address Proof",
      purpose: "Address",
      uploadedOn: "2026-06-05",
      status: "Verified",
    },
  ],
  subjectSelections: [
    {
      id: 1,
      college: "Mother Theresa Institute",
      course: "Diploma in General Nursing",
      term: "Term 1",
      subjects: "Anatomy, Physiology",
      effectiveFrom: "2026-06-01",
      status: "Active",
    },
    {
      id: 2,
      college: "Nursing College",
      course: "Diploma in General Nursing",
      term: "Term 2",
      subjects: "Pharmacology",
      effectiveFrom: "2026-06-10",
      status: "Active",
    },
  ],
  schedules: [
    {
      id: 1,
      college: "Mother Theresa Institute",
      course: "Diploma in General Nursing",
      term: "Term 1",
      examType: "Mid Term",
      date: "2026-07-15",
      status: "Submitted",
    },
    {
      id: 2,
      college: "Nursing College",
      course: "Diploma in General Nursing",
      term: "Term 2",
      examType: "End Term",
      date: "2026-08-20",
      status: "Approved",
    },
  ],
  attendance: [
    {
      id: 1,
      student: "Asha Kumar",
      subject: "Anatomy",
      examType: "Mid Term",
      attendance: "Present",
      uploadedBy: "College Coordinator",
      status: "Submitted",
    },
    {
      id: 2,
      student: "Nivin Raj",
      subject: "Physiology",
      examType: "Mid Term",
      attendance: "Absent",
      uploadedBy: "College Coordinator",
      status: "Verified",
    },
  ],
  subjectMarks: [
    {
      id: 1,
      subject: "Anatomy",
      course: "Diploma in General Nursing",
      term: "Term 1",
      totalMarks: "100",
      passMarks: "35",
      status: "Approved",
    },
    {
      id: 2,
      subject: "Physiology",
      course: "Diploma in General Nursing",
      term: "Term 1",
      totalMarks: "100",
      passMarks: "35",
      status: "Submitted",
    },
  ],
  studentMarks: [
    {
      id: 1,
      student: "Asha Kumar",
      subject: "Anatomy",
      internal: "24",
      exam: "58",
      result: "Pass",
      status: "Submitted",
    },
    {
      id: 2,
      student: "Nivin Raj",
      subject: "Physiology",
      internal: "18",
      exam: "12",
      result: "Fail",
      status: "Verified",
    },
  ],
  marksheets: [
    {
      id: 1,
      student: "Sara D'Souza",
      registrationNo: "REG-2026-0001",
      course: "Diploma in General Nursing",
      division: "First Class",
      referenceNo: "MS-2026-0001",
      status: "Verified",
    },
    {
      id: 2,
      student: "Nivin Raj",
      registrationNo: "REG-2026-0002",
      course: "Diploma in Medical Lab Technology",
      division: "Fail",
      referenceNo: "MS-2026-0002",
      status: "Submitted",
    },
  ],
  reports: [
    {
      id: 1,
      name: "College-wise Enrolment",
      module: "Student",
      frequency: "Monthly",
      owner: "Reports Desk",
      status: "Active",
    },
    {
      id: 2,
      name: "Exam Attendance Report",
      module: "Examination",
      frequency: "On Demand",
      owner: "BOME",
      status: "Active",
    },
    {
      id: 3,
      name: "Course-wise Pass-Fail",
      module: "Marks",
      frequency: "Monthly",
      owner: "BOEN",
      status: "Active",
    },
  ],
  workflows: [
    {
      id: 1,
      task: "Student Detail Verification",
      module: "Student",
      college: "Mother Theresa Institute",
      board: "BOME",
      status: "Submitted",
    },
    {
      id: 2,
      task: "Exam Schedule Approval",
      module: "Examination",
      college: "Nursing College",
      board: "BOEN",
      status: "Verified",
    },
    {
      id: 3,
      task: "Digitally Signed Marksheet",
      module: "Marks",
      college: "Mother Theresa Institute",
      board: "BOME",
      status: "Submitted",
    },
  ],
};
