import {
  FileCheck2,
  Layers,
  ClipboardCheck,
  CircleCheck,
  Pencil,
  FileText,
  LayoutDashboard,
  GraduationCap,
  Settings,
  Upload,
  ShieldCheck,
  UserCheck,
  CalendarCheck,
  ListChecks,
  Users,
  BookOpen,
  BadgeCheck,
  SlidersHorizontal,
  KeyRound,
  Building2,
} from "lucide-react";
import {
  BOARD_ROLES,
  COLLEGE_ROLES,
  VERIFIER_ROLES,
  APPROVER_ROLES,
  ALL_ROLES,
  ENTITY_FIELDS,
} from "./data.js";

// Sidebar / route configuration: key, label, icon, roles allowed, group, type|entity, fields, title, workflow.
export const ROUTES = [
  {
    key: "dashboard",
    label: "Dashboard",
    icon: LayoutDashboard,
    roles: ALL_ROLES,
    group: "Overview",
    type: "dashboard",
  },
  {
    key: "users",
    label: "User Creation",
    icon: Users,
    roles: ["Super Admin"],
    group: "Super Admin",
    entity: "users",
    fields: ENTITY_FIELDS.user,
    title: "User Creation",
  },
  {
    key: "department-admins",
    label: "Department Admins",
    icon: KeyRound,
    roles: ["Super Admin"],
    group: "Super Admin",
    type: "department-admins",
    title: "Department Admins",
  },
  {
    key: "institution-admins",
    label: "Institution Accounts",
    icon: Building2,
    roles: ["Super Admin"],
    group: "Super Admin",
    type: "institution-admins",
    title: "Institution Accounts",
  },
  {
    key: "roles",
    label: "User Roles",
    icon: ShieldCheck,
    roles: ["Super Admin"],
    group: "Super Admin",
    entity: "roles",
    fields: ENTITY_FIELDS.role,
    title: "User Roles",
  },
  {
    key: "mappings",
    label: "User Mapping",
    icon: Layers,
    roles: ["Super Admin"],
    group: "Super Admin",
    entity: "mappings",
    fields: ENTITY_FIELDS.mapping,
    title: "User Mapping",
  },
  {
    key: "features",
    label: "Feature Configuration",
    icon: SlidersHorizontal,
    roles: ["Super Admin"],
    group: "Super Admin",
    entity: "features",
    fields: ENTITY_FIELDS.feature,
    title: "Feature Configuration",
  },
  {
    key: "masters",
    label: "Master Data",
    icon: Settings,
    roles: ["Super Admin"],
    group: "Super Admin",
    entity: "masters",
    fields: ENTITY_FIELDS.master,
    title: "Master Data",
  },
  {
    key: "student-basic",
    label: "Student Basic Details",
    icon: GraduationCap,
    roles: COLLEGE_ROLES,
    group: "College",
    entity: "students",
    fields: ENTITY_FIELDS.student,
    title: "Student Basic Details",
  },
  {
    key: "education",
    label: "Education Details",
    icon: BookOpen,
    roles: COLLEGE_ROLES,
    group: "College",
    entity: "education",
    fields: ENTITY_FIELDS.education,
    title: "Education Details",
  },
  {
    key: "documents",
    label: "Document Upload",
    icon: Upload,
    roles: COLLEGE_ROLES,
    group: "College",
    entity: "documents",
    fields: ENTITY_FIELDS.document,
    title: "Document Upload",
  },
  {
    key: "subject-selection",
    label: "Subject Selection",
    icon: ListChecks,
    roles: COLLEGE_ROLES,
    group: "College",
    entity: "subjectSelections",
    fields: ENTITY_FIELDS.subjectSelection,
    title: "Subject Selection for Term",
  },
  {
    key: "schedule-create",
    label: "Exam Schedule",
    icon: CalendarCheck,
    roles: COLLEGE_ROLES,
    group: "College",
    entity: "schedules",
    fields: ENTITY_FIELDS.schedule,
    title: "Exam Schedule Creation",
  },
  {
    key: "attendance",
    label: "Exam Attendance",
    icon: ClipboardCheck,
    roles: COLLEGE_ROLES,
    group: "College",
    entity: "attendance",
    fields: ENTITY_FIELDS.attendance,
    title: "Exam Attendance Upload",
  },
  {
    key: "student-marks-entry",
    label: "Student Marks Entry",
    icon: Pencil,
    roles: COLLEGE_ROLES,
    group: "College",
    entity: "studentMarks",
    fields: ENTITY_FIELDS.studentMarks,
    title: "Student Marks Entry",
  },
  {
    key: "student-verification",
    label: "Student Verification",
    icon: UserCheck,
    roles: [...BOARD_ROLES, ...VERIFIER_ROLES, ...APPROVER_ROLES],
    group: "Board Workflows",
    entity: "students",
    fields: ENTITY_FIELDS.student,
    title: "Student Verification and Approval",
    workflow: true,
  },
  {
    key: "course-mapping",
    label: "Course Mapping",
    icon: Layers,
    roles: BOARD_ROLES,
    group: "Board Workflows",
    entity: "subjectSelections",
    fields: ENTITY_FIELDS.subjectSelection,
    title: "Course, Subject, Term Mapping",
  },
  {
    key: "schedule-approval",
    label: "Schedule Approval",
    icon: CalendarCheck,
    roles: [...BOARD_ROLES, ...VERIFIER_ROLES, ...APPROVER_ROLES],
    group: "Board Workflows",
    entity: "schedules",
    fields: ENTITY_FIELDS.schedule,
    title: "Exam Schedule Approval",
    workflow: true,
  },
  {
    key: "subject-marks",
    label: "Subject Marks",
    icon: BadgeCheck,
    roles: BOARD_ROLES,
    group: "Board Workflows",
    entity: "subjectMarks",
    fields: ENTITY_FIELDS.subjectMarks,
    title: "Subject Marks Verification",
  },
  {
    key: "marks-approval",
    label: "Marks Approval",
    icon: CircleCheck,
    roles: [...BOARD_ROLES, ...VERIFIER_ROLES, ...APPROVER_ROLES],
    group: "Board Workflows",
    entity: "studentMarks",
    fields: ENTITY_FIELDS.studentMarks,
    title: "Marks Verification and Approval",
    workflow: true,
  },
  {
    key: "marksheet-approval",
    label: "Marksheet Approval",
    icon: FileCheck2,
    roles: [...BOARD_ROLES, ...APPROVER_ROLES],
    group: "Board Workflows",
    entity: "marksheets",
    fields: ENTITY_FIELDS.marksheet,
    title: "Digitally Signed Marksheet Approval",
    workflow: true,
  },
  {
    key: "reports",
    label: "MIS Reports",
    icon: FileText,
    roles: ["Super Admin", "Reports User", ...BOARD_ROLES],
    group: "Reports",
    entity: "reports",
    fields: ENTITY_FIELDS.report,
    title: "MIS Reports",
  },
  {
    key: "institution-portal",
    label: "Institution Portal",
    icon: Building2,
    roles: ["Institution"],
    group: "Institution",
    type: "institution-portal",
    title: "Institution Portal",
  },
  {
    key: "approvals",
    label: "Institution Approvals",
    icon: CircleCheck,
    // Super Admin is allowed here now (permission-wise) but `hidden: true`
    // keeps it out of every auto-generated nav surface (sidebar fallback
    // menu, dashboard module grid) so there's no visible way in yet. When
    // ready: drop `hidden` and add an entry to SUPER_ADMIN_MENU in Sidebar.jsx.
    roles: [...BOARD_ROLES, "Super Admin"],
    group: "Board Workflows",
    type: "approvals",
    title: "Institution Approvals",
    hidden: true,
  },
];
